---
# task/systemd file for dns_resolver_conf
- name: "Configure systemd-resolved"
  ansible.builtin.service:
    name: systemd-resolved
    enabled: "{{ 'true' if not dns_resolv_conf_disable_resolvectl else 'false' }}"
    state: "{{ 'started' if not dns_resolv_conf_disable_resolvectl else 'stopped' }}"
